# POST http://localhost:3001/api/auth/register
# Content-Type: application/json

# {
#   "userName": "Test",
#   "email": "user@example.com",
#   "password": "password123"
# }

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

# GET http://localhost:3001/api/user/userData/