# POST http://localhost:3001/api/auth/register
# Content-Type: application/json

# {
#   "userName": "Test",
#   "email": "user@example.com",
#   "password": "password123"
# }

POST https://chat-app-server-production-1070.up.railway.app/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

# GET http://localhost:3001/api/user/userData/

# GET http://localhost:3001/api/user/addUser?user1_id=91e281fd-74b7-40a3-86c2-f9ce4628d2b3&email=test1@example.com

# userTest2@ss
# 12345

# POST http://localhost:3001/api/user/addUser
# Content-Type: application/json

# {
#   "user1_id": 1383e3b6-f6d8-4fc7-97b3-bdaca3af45c1,
#   "email": test1@asd.c
#   12345
# }

# POST http://localhost:3001/api/user/changeImage
# Content-Type: application/json

# {
#   "userId": "da890174-6490-41b5-9d6e-aeded227512f",
#   "imageURL": "https://i0.wp.com/plopdo.com/wp-content/uploads/2021/11/feature-pic.jpg?fit=537%2C322&ssl=1"
# }